/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 jumping.glb 
Author: Fazbeards (https://sketchfab.com/Fazbeards)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jumping-e33ccb1e75cd426ebb62d6e703fd06a8
Title: Jumping
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useSelector } from "react-redux";
import { useDispatch } from "react-redux";
export default function Model(props) {
  const dispatch = useDispatch();
  const check = useSelector((store) => store.check);
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/jumping.glb");
  // const { actions } = useAnimations(animations, group);
  const { animations: typing } = useGLTF("/jumping.glb");
  typing[0].name = "Typing";
  const { actions } = useAnimations(typing, group);

  useEffect(() => {
    if (check === "JUMP") {
      actions["Typing"].reset().play();
      setTimeout(() => {
        actions["Typing"].stop();
        dispatch({ type: "NOTHING" });
      }, 1100);
    }
  }, [check]);

  useEffect(() => {
    // Check if nodes and materials are loaded
    if (nodes && materials) {
      dispatch({ type: "jumpLoaded" });
    }
  }, [nodes, materials]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="51cffe6aa7f249c4b4461cf51d4b3115fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_10" rotation={[-Math.PI / 2, 0, 0]} />
                  <group
                    name="Object_12"
                    position={[0, 4.393, -20.76]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_14"
                    position={[0, 4.393, -20.76]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Object_16"
                    position={[0, 4.393, -20.76]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group name="Object_18" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_20" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Mario__BodyMT" rotation={[-Math.PI / 2, 0, 0]} />
                  <group
                    name="Mario64HandL__BodyMT"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Mario64HandR__BodyMT"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Cap__CapMT"
                    position={[0, 4.393, -20.76]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="CapHair__HairMT"
                    position={[0, 4.393, -20.76]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group
                    name="Hair__HairMT"
                    position={[0, 4.393, -20.76]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <group name="Face__FaceMT" rotation={[-Math.PI / 2, 0, 0]} />
                  <group
                    name="MarioEye__EyeMT"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.BodyMT}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.HandMT}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.HandMT}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.CapMT}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials.HairMT}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials.HairMT}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.FaceMT}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials.EyeMT}
                    skeleton={nodes.Object_21.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/jumping.glb");
